spring.application.name=customer-service
server.port=5000

addressservice.endpoint=http://localhost:7000


otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc
otel.traces.sampler=always_on
otel.service.name=customer-service