spring.application.name=loan-service
server.port=6000

customerservice.endpoint=http://localhost:5000

otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc
otel.traces.sampler=always_on
otel.service.name=loan-service