spring.application.name=deposit-service
server.port=7090

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/db-ui
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.platform=h2

otel.service.name=deposit-service
otel.traces.sampler=always_on
# DO NOT USE IN PROD
otel.instrumentation.common.db-statement-sanitizer.enabled=false
otel.instrumentation.jdbc.enabled=false


otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc