spring.application.name=address-service

server.port=7000

otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc
otel.traces.sampler=always_on
otel.service.name=address-service